name: Backend CI

on:
  push:
    branches: [main, uat, qa]
  pull_request:
    branches: [main, uat, qa]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore packages
        run: dotnet restore backend/codename-bulldog.sln

      - name: Build solution
        run: dotnet build backend/codename-bulldog.sln --configuration Release

      # Debug tool versions and line-ending behavior
      - name: Log .NET and format versions + Git EOL info
        run: |
          dotnet --version
          dotnet format --version
          git config --get core.autocrlf
          git ls-files --eol

      # Run code formatting check
      - name: Verify code formatting
        run: dotnet format backend/codename-bulldog.sln --verify-no-changes

      # Run tests
      - name: Run tests
        run: dotnet test backend/codename-bulldog.sln --no-build --configuration Release --verbosity normal
