name: Build, Test, and Deploy ASP.Net Core app to Azure Web App - QA

on:
  push:
    branches:
      - qa
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      - name: Restore dependencies
        run: dotnet restore backend/codename-bulldog.sln

      - name: Format check (optional)
        run: dotnet format backend --verify-no-changes --severity info
        continue-on-error: true

      - name: Build
        run: dotnet build backend/codename-bulldog.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test backend/backend.Tests/backend.Tests.csproj --no-build --configuration Release

      - name: Publish
        run: dotnet publish backend/backend.csproj -c Release -o ./publish

      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-qa
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: qa
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-qa

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8079912463B54C9AA99028668C835635 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_808E0D4623F84341AF38EC88CC708F7F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4032813A62354CB0A7B8B5B4ECF903A4 }}

      - name: Deploy to Azure Web App - qa
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "project-bulldog-backend-qa"
          slot-name: "Production"
          package: .
